name: portfolio_elsa
description: "Creating my own portfolio website."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1

environment:
  sdk: '>=3.4.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
flutter_intl:
  enabled: true